language: cpp

compiler:
  - clang
  - gcc

sudo: false

os:
  - linux
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew install gettext;
      brew link gettext --force;
      brew install cppunit;
    fi
#  - [ "$TRAVIS_OS_NAME" = "osx" ] && brew install gcc5
# Don't use real gcc on OS X, problems arise when
# Hunspell built with gcc is linked with cppunit built with clang.
# Homebrew builds are build with clang
#before_script:
#  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script:
  - autoreconf -i && ./configure && make && make check; fi
#  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then autoreconf -i -I /usr/local/share/aclocal && ./configure && make && make check; fi
# might be needed for future
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - automake
    - autopoint
    - gcc-5
    - g++-5
    - libcppunit-dev
